#!/usr/bin/env ruby

require "gosu"

module ZOrder
	Background, Sprites, UI = *0..2
end

module Size
	Rows = 14
	Columns = 18
end

require_relative "lib/player"
require_relative "lib/windows"
require_relative "lib/tile"
require_relative "lib/item"
require_relative "lib/room"
require_relative "lib/map"

width = Size::Columns * 32
height = Size::Rows * 33

start_win = StartWindow.new(width, height)
start_win.show
