#!/usr/bin/env ruby

require "gosu"

module ZOrder
	Background, Sprites, UI = *0..2
end

require_relative "lib/player"
require_relative "lib/windows"

rows = 14
columns = 18

width = columns * 32
height = rows * 33

# start_win = StartWindow.new(width, height)
# start_win.show

game_win = GameWindow.new(width, height)
game_win.show
